import assert from "node:assert/strict";
import { afterEach, test } from "node:test";
import { sendContactNotification } from "./contact-notification.ts";
const context = { fields: { firstName: "Jane", lastName: "Doe", email: "jane@example.com", phone: "2505550100", message: "Please contact me about an assessment." }, source: "contact" as const, jotformSubmissionId: "sub_123" };
const ENV_KEYS = ["RESEND_API_KEY","RESEND_FROM_EMAIL","CONTACT_NOTIFICATION_EMAIL","SMTP_HOST","SMTP_PORT","SMTP_USER","SMTP_PASS","SMTP_FROM_EMAIL","SMTP_FROM_NAME"] as const;
const originalEnv = Object.fromEntries(ENV_KEYS.map((key) => [key, process.env[key]]));
function restoreEnv(){ for(const key of ENV_KEYS){ const value=originalEnv[key]; if(value===undefined) delete process.env[key]; else process.env[key]=value; } }
function clearNotificationEnv(){ for(const key of ENV_KEYS) delete process.env[key]; }
function configureSmtp(){ process.env.SMTP_HOST="mail.example.test"; process.env.SMTP_USER="contact@example.test"; process.env.SMTP_PASS="placeholder"; }
afterEach(restoreEnv);
test("Resend sends a styled reply-friendly contact notification", async()=>{ clearNotificationEnv(); process.env.RESEND_API_KEY="re_test"; process.env.RESEND_FROM_EMAIL="NeuroLinks Website <notifications@neurolinks.ca>"; process.env.CONTACT_NOTIFICATION_EMAIL="contact@neurolinks.ca"; let smtpCalls=0; const response=await sendContactNotification(context, async(input,init={})=>{ assert.equal(String(input),"https://api.resend.com/emails"); const headers=new Headers(init.headers); assert.equal(headers.get("Authorization"),"Bearer re_test"); assert.equal(headers.get("Idempotency-Key"),"neurolinks-contact/sub_123"); const body=JSON.parse(String(init.body)) as Record<string,unknown>; assert.equal(body.reply_to,"jane@example.com"); assert.equal(body.subject,"New website inquiry — Jane Doe"); const text=String(body.text); assert.equal(text.includes("New website inquiry from Jane Doe"),true); assert.equal(text.includes("Email: jane@example.com"),true); assert.equal(text.includes("Phone: 250-555-0100"),true); assert.equal(text.includes("Submitted through neurolinks.ca/contact/"),true); assert.equal(text.includes("Jotform"),false); assert.equal(text.includes("Resend"),false); const html=String(body.html); assert.equal(html.includes("New Website Inquiry"),true); assert.equal(html.includes("Jane Doe"),true); assert.equal(html.includes('href="mailto:jane@example.com"'),true); assert.equal(html.includes("250-555-0100"),true); assert.equal(html.includes("tel:"),false); assert.equal(html.includes('name="format-detection" content="telephone=no"'),true); assert.equal(html.includes("neurolinks.ca/contact/"),true); assert.equal(html.includes(context.fields.message),true); return new Response(JSON.stringify({id:"email_123"}),{status:200,headers:{"content-type":"application/json"}}); }, async()=>{smtpCalls+=1;}); assert.deepEqual(response,{primary:"sent",resendEmailId:"email_123"}); assert.equal(smtpCalls,0); });
test("shared contact notification uses the correct source footer for all three forms", async()=>{ clearNotificationEnv(); process.env.RESEND_API_KEY="re_test"; const sources = [
  { source: "contact" as const, path: "/contact/" },
  { source: "veterans" as const, path: "/veterans-tms-treatment/" },
  { source: "advertising-landing" as const, path: "/neurolinks-psychiatry-nanaimo-bc/" },
];
for (const entry of sources) {
  await sendContactNotification({ ...context, source: entry.source, jotformSubmissionId: `sub_${entry.source}` }, async(_input,init={})=>{ const body=JSON.parse(String(init.body)) as Record<string,unknown>; assert.equal(String(body.html).includes(`neurolinks.ca${entry.path}`),true); assert.equal(String(body.text).includes(`neurolinks.ca${entry.path}`),true); return new Response(JSON.stringify({id:`email_${entry.source}`}),{status:200,headers:{"content-type":"application/json"}}); });
}
});
test("Resend failure sends the same reply-friendly SMTP contact email plus technical alert", async()=>{ clearNotificationEnv(); process.env.RESEND_API_KEY="re_test"; configureSmtp(); const smtpMessages:Array<{to:string;replyTo?:string;subject:string;text:string}>=[]; const result=await sendContactNotification(context, async()=>new Response(JSON.stringify({name:"validation_error",message:"Sender domain is not verified"}),{status:403,headers:{"content-type":"application/json"}}), async(message)=>{smtpMessages.push(message);}); assert.equal(result.primary,"failed"); assert.equal(result.fallbackContact,"sent"); assert.equal(result.fallbackAlert,"sent"); assert.equal(smtpMessages.length,2); const contact=smtpMessages[0]; assert.equal(contact.to,"contact@neurolinks.ca"); assert.equal(contact.replyTo,"jane@example.com"); assert.equal(contact.subject,"New website inquiry — Jane Doe"); assert.equal(contact.text.includes("New website inquiry from Jane Doe"),true); assert.equal(contact.text.includes("Phone: 250-555-0100"),true); assert.equal(contact.text.includes(context.fields.message),true); assert.equal(contact.text.includes("Resend"),false); assert.equal(contact.text.includes("Jotform"),false); const alert=smtpMessages[1]; assert.equal(alert.replyTo,undefined); assert.equal(alert.subject,"Website notification fallback activated - Jotform sub_123"); assert.equal(alert.text.includes("saved successfully in Jotform"),true); assert.equal(alert.text.includes(context.fields.message),false); });
test("missing Resend configuration falls back to SMTP without failing inquiry",async()=>{ clearNotificationEnv(); configureSmtp(); const smtpMessages:Array<{subject:string}>=[]; const result=await sendContactNotification(context,async()=>{throw new Error("Resend fetch should not run without an API key");},async(message)=>{smtpMessages.push({subject:message.subject});}); assert.equal(result.primary,"not-configured"); assert.equal(result.fallbackContact,"sent"); assert.equal(result.fallbackAlert,"sent"); assert.equal(smtpMessages[0].subject,"New website inquiry — Jane Doe"); assert.equal(smtpMessages.length,2); });
