import { defineField, defineType } from "sanity";
import { INSIGHTS_TOPICS, PATIENT_INFORMATION_WARNING } from "@/lib/insights";
import { articleBodyMembers } from "./blocks";

export const article = defineType({
  name: "article",
  title: "Article",
  type: "document",
  description: PATIENT_INFORMATION_WARNING,
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "medical", title: "Authorship" },
    { name: "related", title: "Related" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summary",
      title: "Short summary",
      type: "text",
      rows: 3,
      group: "content",
      description: "One or two sentences. Shown on cards and under the article title.",
      validation: (rule) => rule.required().max(280),
    }),
    defineField({
      name: "category",
      type: "reference",
      to: [{ type: "category" }],
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "topics",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: {
        list: INSIGHTS_TOPICS.map((topic) => ({ title: topic.title, value: topic.slug })),
        layout: "grid",
      },
    }),
    defineField({
      name: "featuredImage",
      title: "Featured image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      description: PATIENT_INFORMATION_WARNING,
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
          validation: (rule) => rule.required().min(8),
        }),
        defineField({
          name: "caption",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "keyPoints",
      title: "Key points",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      description: "Shown near the top of the article. Keep each point to one sentence.",
    }),
    defineField({
      name: "body",
      title: "Article body",
      type: "array",
      group: "content",
      of: articleBodyMembers,
      description:
        "Use Insert to add structured blocks. Presentation is controlled by the website. Avoid miracle, cure, revolutionary, guaranteed, or coverage-is-automatic language.",
    }),
    defineField({
      name: "author",
      type: "reference",
      to: [{ type: "person" }],
      group: "medical",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "medicalReviewer",
      title: "Medical reviewer",
      type: "reference",
      to: [{ type: "person" }],
      group: "medical",
    }),
    defineField({
      name: "publishedAt",
      title: "Published date",
      type: "datetime",
      group: "medical",
      description: "Required to appear on the public site. Leave empty while the article is a draft.",
    }),
    defineField({
      name: "lastReviewedAt",
      title: "Last medically reviewed date",
      type: "date",
      group: "medical",
    }),
    defineField({
      name: "readingTime",
      title: "Estimated reading time (minutes)",
      type: "number",
      group: "content",
      description: "Leave blank to estimate from the article body.",
      validation: (rule) => rule.integer().min(1).max(60),
    }),
    defineField({
      name: "featured",
      title: "Featured article",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "sortOrder",
      title: "Article order",
      type: "number",
      group: "content",
      description: "Lower numbers appear first. Featured articles still appear in the featured slot.",
    }),
    defineField({
      name: "relatedArticles",
      title: "Related articles",
      type: "array",
      group: "related",
      of: [{ type: "reference", to: [{ type: "article" }] }],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: "references",
      title: "References",
      type: "array",
      group: "related",
      of: [{ type: "reference", to: [{ type: "citationSource" }] }],
    }),
    defineField({
      name: "ctaHref",
      title: "Article CTA link",
      type: "url",
      group: "related",
      description:
        "Optional. Veterans articles should usually use /veterans/#veterans-contact. Other articles can use a treatment page or /contact/.",
      validation: (rule) => rule.uri({ allowRelative: true, scheme: ["http", "https"] }),
    }),
    defineField({
      name: "ctaLabel",
      title: "Article CTA label",
      type: "string",
      group: "related",
    }),
    defineField({
      name: "seoTitle",
      title: "SEO title",
      type: "string",
      group: "seo",
      validation: (rule) => rule.max(70),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta description",
      type: "text",
      rows: 3,
      group: "seo",
      validation: (rule) => rule.max(170),
    }),
    defineField({
      name: "socialTitle",
      title: "Social-sharing title",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "socialDescription",
      title: "Social-sharing description",
      type: "text",
      rows: 3,
      group: "seo",
    }),
    defineField({
      name: "socialImage",
      title: "Social-sharing image",
      type: "image",
      group: "seo",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "canonicalUrl",
      title: "Canonical URL override",
      type: "url",
      group: "seo",
      validation: (rule) => rule.uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "indexable",
      title: "Allow search indexing",
      type: "boolean",
      group: "seo",
      initialValue: true,
      description: "Turn off for published articles that should remain noindex.",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "summary",
      media: "featuredImage",
      featured: "featured",
    },
    prepare: ({ title, subtitle, media, featured }) => ({
      title: featured ? `★ ${title}` : title,
      subtitle,
      media,
    }),
  },
  orderings: [
    { title: "Published date, newest", name: "publishedDesc", by: [{ field: "publishedAt", direction: "desc" }] },
    { title: "Editorial order", name: "sortOrder", by: [{ field: "sortOrder", direction: "asc" }] },
    { title: "Title", name: "title", by: [{ field: "title", direction: "asc" }] },
  ],
});
