type PdfItem = {
  label: string;
  answer: string;
  score: number | null;
};

export type QuestionnairePdfInput = {
  patientName: string;
  patientEmail?: string | null;
  questionnaireName: string;
  questionnaireCode: string;
  submittedAt: string;
  totalScore: number;
  severity?: string | null;
  obsessionScore?: number | null;
  compulsionScore?: number | null;
  items: PdfItem[];
};

function ascii(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[–—]/g, "-")
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, "...")
    .replace(/[^\x20-\x7E\n]/g, "?");
}

function esc(value: string) {
  return ascii(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrap(value: string, max = 92) {
  const words = ascii(value).replace(/\s+/g, " ").trim().split(" ").filter(Boolean);
  if (!words.length) return [""];
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (!line) {
      line = word;
      continue;
    }
    if (`${line} ${word}`.length <= max) line += ` ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function text(font: "F1" | "F2", size: number, x: number, y: number, value: string) {
  return `BT /${font} ${size} Tf ${x} ${y} Td (${esc(value)}) Tj ET`;
}

function line(x1: number, y1: number, x2: number, y2: number, gray = 0.86) {
  return `${gray} G 0.7 w ${x1} ${y1} m ${x2} ${y2} l S 0 G`;
}

function pageStream(input: QuestionnairePdfInput, pageItems: PdfItem[], pageNumber: number, pageCount: number, startIndex: number) {
  const out: string[] = [];
  let y = 760;

  out.push(text("F2", 17, 48, y, "NeuroLinks Clinical Questionnaire Result"));
  y -= 25;
  out.push(text("F2", 13, 48, y, input.questionnaireName));
  y -= 19;
  out.push(text("F1", 10, 48, y, `Patient: ${input.patientName}`));
  y -= 15;
  if (input.patientEmail) {
    out.push(text("F1", 9, 48, y, `Email: ${input.patientEmail}`));
    y -= 14;
  }
  out.push(text("F1", 9, 48, y, `Submitted: ${input.submittedAt}`));
  y -= 14;
  const summary = [`Total score: ${input.totalScore}`];
  if (input.severity) summary.push(`Severity: ${input.severity}`);
  if (input.questionnaireCode === "ybocs") {
    if (input.obsessionScore !== null && input.obsessionScore !== undefined) summary.push(`Obsession: ${input.obsessionScore}`);
    if (input.compulsionScore !== null && input.compulsionScore !== undefined) summary.push(`Compulsion: ${input.compulsionScore}`);
  }
  out.push(text("F2", 10, 48, y, summary.join("   |   ")));
  y -= 18;
  out.push(line(48, y, 548, y));
  y -= 18;

  pageItems.forEach((item, localIndex) => {
    const itemNo = startIndex + localIndex + 1;
    const labelLines = wrap(`${itemNo}. ${item.label}`, 78);
    for (const label of labelLines) {
      out.push(text("F2", 9.5, 48, y, label));
      y -= 13;
    }
    const answerLines = wrap(item.answer || "-", 88);
    for (const answer of answerLines) {
      out.push(text("F1", 9, 58, y, answer));
      y -= 12;
    }
    if (item.score !== null) {
      out.push(text("F2", 8.5, 58, y, `Item score: ${item.score}`));
      y -= 11;
    }
    y -= 4;
    out.push(line(48, y, 548, y, 0.92));
    y -= 12;
  });

  out.push(text("F1", 8, 48, 28, `Generated by NeuroLinks  |  Page ${pageNumber} of ${pageCount}`));
  return out.join("\n");
}

function paginate(input: QuestionnairePdfInput) {
  const pages: Array<{ items: PdfItem[]; startIndex: number }> = [];
  let current: PdfItem[] = [];
  let currentUnits = 0;
  let startIndex = 0;

  for (let i = 0; i < input.items.length; i += 1) {
    const item = input.items[i];
    const units = Math.max(3, wrap(item.label, 78).length + wrap(item.answer, 88).length + (item.score === null ? 0 : 1) + 1);
    if (current.length && currentUnits + units > 43) {
      pages.push({ items: current, startIndex });
      startIndex += current.length;
      current = [];
      currentUnits = 0;
    }
    current.push(item);
    currentUnits += units;
  }
  if (current.length || !pages.length) pages.push({ items: current, startIndex });
  return pages;
}

export function buildQuestionnairePdf(input: QuestionnairePdfInput): Uint8Array {
  const pages = paginate(input);
  const objects: string[] = [];

  // 1 catalog, 2 pages root, 3 regular font, 4 bold font
  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";

  const pageRefs: number[] = [];
  let objectNo = 5;
  pages.forEach((page, index) => {
    const pageNo = objectNo++;
    const contentNo = objectNo++;
    pageRefs.push(pageNo);
    const stream = pageStream(input, page.items, index + 1, pages.length, page.startIndex);
    objects[contentNo] = `<< /Length ${Buffer.byteLength(stream, "ascii")} >>\nstream\n${stream}\nendstream`;
    objects[pageNo] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentNo} 0 R >>`;
  });
  objects[2] = `<< /Type /Pages /Kids [${pageRefs.map((ref) => `${ref} 0 R`).join(" ")}] /Count ${pageRefs.length} >>`;

  let pdf = "%PDF-1.4\n%NLNK\n";
  const offsets: number[] = [0];
  for (let i = 1; i < objects.length; i += 1) {
    offsets[i] = Buffer.byteLength(pdf, "ascii");
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(pdf, "ascii");
  pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let i = 1; i < objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Uint8Array(Buffer.from(pdf, "ascii"));
}
