"use client";
import { useMemo,useState } from "react";

type Code="bdii"|"bai"|"ybocs"|"pss";
const LABELS:Record<Code,string>={bdii:"BDI-II",bai:"BAI",ybocs:"Y-BOCS",pss:"PSS"};
type Patient={id:string;firstName:string;lastName:string;email:string|null;phone:string|null};
type Row={submissionId:string;jotformName:string;vcitaPatient:Patient|null;jotformDate:string|null;supabaseDate:string|null;jotformTotal:number|null;supabaseTotal:number|null;dateMatch:boolean;totalMatch:boolean;itemMismatchCount:number;itemMatchCount:number;status:"match"|"mismatch"|"not_imported"};
type Detail=Row&{items:Array<{key:string;title:string;jotformText:string;jotformScore:number|null;supabaseText:string;supabaseScore:number|null;textMatch:boolean;scoreMatch:boolean;match:boolean}>};
type Resp={ok:true;generatedAt?:string;summary:{totalJotform:number;imported:number;fullMatches:number;mismatches:number;notImported:number};rows:Row[]}|{ok:false;error:string};
type DResp={ok:true;detail:Detail}|{ok:false;error:string};

export function HistoricalVerificationPortal(){
 const [code,setCode]=useState<Code>("bdii"),[data,setData]=useState<Resp|null>(null),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(false),[detailLoading,setDetailLoading]=useState(false),[filter,setFilter]=useState<"all"|Row["status"]>("mismatch"),[query,setQuery]=useState("");
 async function run(){
  setLoading(true);setDetail(null);
  try{const r=await fetch(`/form/api/import/verify/?code=${code}`,{cache:"no-store"});setData(await r.json() as Resp);}catch{setData({ok:false,error:"Could not load verification report."});}finally{setLoading(false);}
 }
 async function open(id:string){
  setDetailLoading(true);setDetail(null);
  try{const r=await fetch(`/form/api/import/verify/?code=${code}&submissionId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json() as DResp;if(d.ok)setDetail(d.detail);}finally{setDetailLoading(false);}
 }
 const rows=useMemo(()=>!data?.ok?[]:data.rows.filter(r=>(filter==="all"||r.status===filter)&&(!query.trim()||[r.jotformName,r.submissionId,r.vcitaPatient?[r.vcitaPatient.firstName,r.vcitaPatient.lastName,r.vcitaPatient.email,r.vcitaPatient.phone].filter(Boolean).join(" "):""].join(" ").toLowerCase().includes(query.trim().toLowerCase()))),[data,filter,query]);
 return <div>
  <label style={{display:"block",marginBottom:16}}><span style={{display:"block",fontWeight:700,marginBottom:6}}>Questionnaire to verify</span><select value={code} onChange={e=>{setCode(e.target.value as Code);setData(null);setDetail(null);}} style={{padding:"10px 12px",border:"1px solid #d1d5db",borderRadius:8,minWidth:260}}>{Object.entries(LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
  <div style={{padding:16,border:"1px solid #bfdbfe",background:"#eff6ff",borderRadius:10,marginBottom:18}}><strong>Read-only verification</strong><p style={{margin:"6px 0 0"}}>Compares original Jotform submissions with imported Supabase records, including patient linkage, date, total score, and item responses.</p></div>
  <button onClick={run} disabled={loading} style={{padding:"11px 16px",border:0,borderRadius:8,background:"#111827",color:"#fff",fontWeight:700}}>{loading?"Checking migration…":`Run ${LABELS[code]} verification`}</button>
  {data&&!data.ok?<p style={{marginTop:16,padding:12,background:"#fef2f2"}}>{data.error}</p>:null}
  {data?.ok?<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:12,margin:"20px 0"}}>{[["Jotform",data.summary.totalJotform],["Imported",data.summary.imported],["Full matches",data.summary.fullMatches],["Mismatches",data.summary.mismatches],["Not imported",data.summary.notImported]].map(([l,v])=><div key={String(l)} style={{padding:14,border:"1px solid #e5e7eb",borderRadius:10}}><div style={{color:"#6b7280",fontSize:13}}>{l}</div><div style={{fontSize:26,fontWeight:800}}>{v}</div></div>)}</div>
  <div style={{display:"flex",gap:10,marginBottom:14}}><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)} style={{padding:9,border:"1px solid #d1d5db",borderRadius:8}}><option value="all">All</option><option value="match">Full matches</option><option value="mismatch">Mismatches</option><option value="not_imported">Not imported</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter by patient or submission ID" style={{flex:1,padding:9,border:"1px solid #d1d5db",borderRadius:8}}/></div>
  <div style={{overflowX:"auto",border:"1px solid #e5e7eb",borderRadius:10}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr>{["Jotform patient","vcita patient","Jotform score","Supabase score","Item mismatches","Status"].map(h=><th key={h} style={{textAlign:"left",padding:10}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.submissionId} onClick={()=>open(r.submissionId)} style={{cursor:"pointer",borderTop:"1px solid #f3f4f6"}}><td style={{padding:10}}><strong style={{textDecoration:"underline"}}>{r.jotformName||"Unnamed"}</strong><div style={{fontSize:12,color:"#9ca3af"}}>{r.submissionId}</div></td><td style={{padding:10}}>{r.vcitaPatient?[r.vcitaPatient.firstName,r.vcitaPatient.lastName].filter(Boolean).join(" "):"—"}</td><td style={{padding:10}}>{r.jotformTotal??"—"}</td><td style={{padding:10}}>{r.supabaseTotal??"—"}</td><td style={{padding:10,fontWeight:r.itemMismatchCount?800:400}}>{r.itemMismatchCount}</td><td style={{padding:10,fontWeight:700}}>{r.status==="match"?"Match":r.status==="mismatch"?"Mismatch":"Not imported"}</td></tr>)}</tbody></table></div>
  {detailLoading?<p>Loading item comparison…</p>:null}
  {detail?<section style={{marginTop:22,paddingTop:18,borderTop:"2px solid #e5e7eb"}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h3 style={{margin:0}}>{detail.jotformName||"Unnamed"} — {LABELS[code]} item verification</h3><p style={{color:"#4b5563"}}>vcita: {detail.vcitaPatient?[detail.vcitaPatient.firstName,detail.vcitaPatient.lastName].filter(Boolean).join(" "):"not resolved"} · Jotform total {detail.jotformTotal??"—"} · Supabase total {detail.supabaseTotal??"—"}</p></div><button onClick={()=>setDetail(null)} style={{border:0,background:"transparent",textDecoration:"underline"}}>Close</button></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Item","Jotform answer","Supabase answer","Score/index","Check"].map(h=><th key={h} style={{textAlign:"left",padding:8}}>{h}</th>)}</tr></thead><tbody>{detail.items.map(i=><tr key={i.key} style={{borderTop:"1px solid #f3f4f6",background:i.match?"#fff":"#fef2f2"}}><td style={{padding:9,fontWeight:700}}>{i.title}</td><td style={{padding:9}}>{i.jotformText||"—"}</td><td style={{padding:9}}>{i.supabaseText||"—"}</td><td style={{padding:9}}>{i.jotformScore??"—"} / {i.supabaseScore??"—"}</td><td style={{padding:9,fontWeight:700}}>{i.match?"Match":"Mismatch"}</td></tr>)}</tbody></table></div></section>:null}</>:null}
 </div>
}