/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    insights: Insight;
    media: Media;
    categories: Category;
    authors: Author;
    references: Reference;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    insights: InsightsSelect<false> | InsightsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'insights-settings': InsightsSetting;
  };
  globalsSelect: {
    'insights-settings': InsightsSettingsSelect<false> | InsightsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Do not enter identifiable patient information into article content, images, captions or editorial notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  /**
   * The headline readers see. Also the default SEO title.
   */
  title: string;
  /**
   * One or two sentences. Shown on cards, under the article title, and used as the default meta description.
   */
  summary: string;
  /**
   * Shown in a panel near the top of the article. Keep each point to one sentence.
   */
  keyPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Write here. Use Heading for sections, and the block menu for key points, evidence summaries, images and callouts.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The clinician who wrote the article.
   */
  author: number | Author;
  /**
   * The clinician who checked the medical content. Shown in the article byline.
   */
  medicalReviewer?: (number | null) | Author;
  /**
   * Also used as the article's modified date for search engines.
   */
  lastReviewedAt?: string | null;
  /**
   * Up to three. Leave blank and NeuroLinks will suggest articles from the same topics.
   */
  relatedArticles?: (number | Insight)[] | null;
  /**
   * Numbered and rendered at the end of the article. Inline reference markers point at this list.
   */
  references?: (number | Reference)[] | null;
  /**
   * Optional. Leave blank to use the topic default: Veterans articles link to the Veterans contact form, others to the matching treatment page or /contact/.
   */
  ctaHref?: string | null;
  ctaLabel?: string | null;
  /**
   * Falls back to the article title.
   */
  seoTitle?: string | null;
  /**
   * Falls back to the short summary.
   */
  metaDescription?: string | null;
  /**
   * Falls back to the SEO title, then the article title.
   */
  socialTitle?: string | null;
  /**
   * Falls back to the meta description.
   */
  socialDescription?: string | null;
  /**
   * Falls back to the featured image, then the NeuroLinks default share image.
   */
  socialImage?: (number | null) | Media;
  /**
   * Leave blank. The canonical URL is https://neurolinks.ca/insights/[slug]/ unless this is set.
   */
  canonicalUrl?: string | null;
  /**
   * Untick for published articles that should stay out of Google and the sitemap.
   */
  indexable?: boolean | null;
  /**
   * The last part of the public URL. Left blank, it is generated from the title. Clear it to regenerate.
   */
  slug?: string | null;
  category: number | Category;
  /**
   * Drives the topic filters on /insights/ and the Veterans grouping.
   */
  topics?:
    | (
        | 'veterans-and-coverage'
        | 'tms'
        | 'ketamine-and-spravato'
        | 'treatment-resistant-depression'
        | 'depression'
        | 'ptsd-and-anxiety'
      )[]
    | null;
  /**
   * Used on cards, at the top of the article and as the default social image. Alternative text comes from the image record.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Optional. Leave blank to use the alternative text stored with the image.
   */
  featuredImageAlt?: string | null;
  /**
   * Required before the article can appear publicly. Set automatically when you publish.
   */
  publishedAt?: string | null;
  /**
   * Shown in the large slot at the top of /insights/.
   */
  featured?: boolean | null;
  /**
   * Leave blank to estimate from the article body.
   */
  readingTime?: number | null;
  /**
   * Lower numbers appear first. Leave blank to order by published date.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Authors and medical reviewers. Only record roles and credentials the clinician actually holds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Public role, for example Psychiatrist. Do not invent titles.
   */
  role: string;
  /**
   * Optional post-nominals, for example MD, FRCPC. Shown next to the name on the article.
   */
  credentials?: string | null;
  /**
   * One or two sentences. Shown in the article authorship panel.
   */
  bio?: string | null;
  /**
   * Do not enter identifiable patient information into article content, images, captions or editorial notes.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Do not enter identifiable patient information into article content, images, captions or editorial notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and for readers whose images fail to load. Never describe an identifiable patient.
   */
  alt: string;
  /**
   * Optional. Shown under the image on the public page.
   */
  caption?: string | null;
  /**
   * Optional attribution, shown with the caption.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Studies, reviews and official documents cited by Insights articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  /**
   * The article, chapter or document title.
   */
  title: string;
  authors?: string | null;
  publisher?: string | null;
  year?: number | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  /**
   * DOI only, without https://doi.org/.
   */
  doi?: string | null;
  pubmedUrl?: string | null;
  /**
   * Used when there is no DOI or PubMed record.
   */
  url?: string | null;
  /**
   * Internal context for editors. Never shown on the public page.
   */
  editorialNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sections such as TMS or Veterans. The category name appears above the article title.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * The last part of the public URL. Left blank, it is generated from the title. Clear it to regenerate.
   */
  slug?: string | null;
  /**
   * Internal note about what belongs in this category.
   */
  description?: string | null;
  tone?: ('navy' | 'blue' | 'gold' | 'sage' | 'teal') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to edit NeuroLinks Insights. Keep this list short.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the admin header and in version history.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  keyPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?: T;
  author?: T;
  medicalReviewer?: T;
  lastReviewedAt?: T;
  relatedArticles?: T;
  references?: T;
  ctaHref?: T;
  ctaLabel?: T;
  seoTitle?: T;
  metaDescription?: T;
  socialTitle?: T;
  socialDescription?: T;
  socialImage?: T;
  canonicalUrl?: T;
  indexable?: T;
  slug?: T;
  category?: T;
  topics?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  publishedAt?: T;
  featured?: T;
  readingTime?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  tone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  credentials?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  title?: T;
  authors?: T;
  publisher?: T;
  year?: T;
  volume?: T;
  issue?: T;
  pages?: T;
  doi?: T;
  pubmedUrl?: T;
  url?: T;
  editorialNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Wording on the Insights index page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-settings".
 */
export interface InsightsSetting {
  id: number;
  /**
   * The main heading at the top of /insights/.
   */
  introHeading?: string | null;
  introBody?: string | null;
  /**
   * The statement explaining who writes and reviews NeuroLinks Insights.
   */
  medicalAuthorship?: string | null;
  contactHeading?: string | null;
  contactBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-settings_select".
 */
export interface InsightsSettingsSelect<T extends boolean = true> {
  introHeading?: T;
  introBody?: T;
  medicalAuthorship?: T;
  contactHeading?: T;
  contactBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyPointsBox".
 */
export interface KeyPointsBox {
  heading?: string | null;
  points?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'keyPointsBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EvidenceSummaryBlock".
 */
export interface EvidenceSummaryBlock {
  /**
   * For example: randomized controlled trial, meta-analysis.
   */
  studyType?: string | null;
  population?: string | null;
  mainFinding?: string | null;
  /**
   * Required. If the comparison is indirect rather than head-to-head, say so here.
   */
  limitation: string;
  /**
   * DOI only, without https://doi.org/.
   */
  doi?: string | null;
  url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'evidenceSummary';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClinicalNoteBlock".
 */
export interface ClinicalNoteBlock {
  heading?: string | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clinicalNote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImportantLimitationBlock".
 */
export interface ImportantLimitationBlock {
  heading?: string | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'importantLimitation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VacCoverageNoteBlock".
 */
export interface VacCoverageNoteBlock {
  /**
   * Keep clinical suitability, funding eligibility, preauthorization and availability separate. Never imply that VAC authorization or payment is guaranteed.
   */
  heading?: string | null;
  suitability: string;
  funding: string;
  preauthorization: string;
  availability: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vacCoverageNote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessTimelineBlock".
 */
export interface ProcessTimelineBlock {
  heading?: string | null;
  intro?: string | null;
  steps?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  /**
   * Do not rank treatments as universally superior. Note indirect comparisons here or in the footnote.
   */
  caption?: string | null;
  columns?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        heading: string;
        cells?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithCaptionBlock".
 */
export interface ImageWithCaptionBlock {
  /**
   * Do not enter identifiable patient information into article content, images, captions or editorial notes.
   */
  image: number | Media;
  /**
   * Leave blank to use the caption stored with the image.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageWithCaption';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedReadingBlock".
 */
export interface RelatedReadingBlock {
  heading?: string | null;
  articles?: (number | Insight)[] | null;
  links?:
    | {
        title: string;
        /**
         * For example /veterans/ or /contact/.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedReading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContextualCtaBlock".
 */
export interface ContextualCtaBlock {
  heading?: string | null;
  body?: string | null;
  label?: string | null;
  /**
   * Leave blank to use the article's topic default (contact, Veterans, or a treatment page).
   */
  href?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contextualCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReferencesSectionBlock".
 */
export interface ReferencesSectionBlock {
  /**
   * Use only when references belong mid-article. The article's own References list still renders at the end.
   */
  heading?: string | null;
  sources?: (number | Reference)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'referencesSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EditorialDiagramBlock".
 */
export interface EditorialDiagramBlock {
  diagram: 'vacPathway' | 'symptomOverlap' | 'neuralMotif';
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'editorialDiagram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitationInlineBlock".
 */
export interface CitationInlineBlock {
  /**
   * Matches the numbered item in the article references list.
   */
  number: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'citation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}